// Necessary imports for ag-grid
import {AgGridProvider, AgGridReact} from 'ag-grid-react';
import { AllCommunityModule } from 'ag-grid-community';
import { themeBalham } from 'ag-grid-community';
import { useEffect, useState } from 'react';
import {GenderDropdown} from './components/GenderDropdown';
import {useGetAllCharactersQuery} from './features/apiSlice';
import './App.css'
const modules = [AllCommunityModule];

// Editable column logic
let editableGender = "Male";
function isEditable(params){
  return params.data.gender === editableGender;
}

function App(){
  const [rowData, setRowData] = useState([]);   // State to hold the row data fetched from the API

  // Grid options including column definitions and types
  const gridOptions = {
  colData:[
    {field: 'id', headerName:'ID',sortable: true}, // Column for ID with sorting enabled
    {field: 'name', headerName:'Name',filter:true, editable: true}, // Column for Name with filtering and editing enabled
    {field: 'status', headerName:'Status',editable: true, cellEditor: 'agSelectCellEditor', cellEditorParams: {values: ['Dead','Alive','Unknown']}}, // Column for Status with editing enabled and a dropdown editor
    {field: 'species', headerName:'Species'}, // Column for Species
    {field: 'gender', headerName:'Gender', editable: true, cellEditor: GenderDropdown }, // Column for Gender with editing enabled using the custom GenderDropdown component
    {field: 'origin.name', headerName:'Origin'}, // Column for Origin
    {field: 'location.name', headerName:'Current Location',type: "specialColumn"} // Column for Current Location with custom editable logic
    ],

    // Custom column types to handle editable logic and styling
    columnTypes:{
      specialColumn:{
        editable: (params) => {
          return isEditable(params) // Check if the cell is editable based on the gender
        },
        cellStyle: (params) => {
          if(!isEditable(params)){
            return {backgroundColor: '#000000', color: '#ffffff'} // Style for non-editable cells
          }
        }
      }
    }

  }
  
  // Fetching data from the API using the custom hook generated by RTK Query
  const {data} = useGetAllCharactersQuery();

  // Effect to update the row data when the API data changes
  useEffect(() => {
    if(data){
      setRowData(data.results); // Set the row data to the results from the API
    }
  }, [data]);

  // Render the ag-grid with the fetched data and defined columns

  return(
      <AgGridProvider modules={modules}>
        <div style={{height: 500}}>
          <AgGridReact 
            theme = {themeBalham}
            rowData = {rowData}
            columnDefs = {gridOptions.colData}
            columnTypes={gridOptions.columnTypes}>
          </AgGridReact>
        </div>
      </AgGridProvider>
  )
}

export default App;