import {AgGridProvider, AgGridReact} from 'ag-grid-react';
import { AllCommunityModule} from 'ag-grid-community';
import { themeBalham, ColDef } from 'ag-grid-community';
import { useEffect, useState } from 'react';
import {GenderDropdown} from './components/GenderDropdown';
import {useGetAllCharactersQuery, Character} from './features/apiSlice';

const modules = [AllCommunityModule];

// Editable column logic
const editableGender = "Male";
function isEditable(params: {data: Character}){
  return params.data.gender === editableGender;
}

export function App(){
  const [rowData, setRowData] = useState<Character[]>([]);   

  // Grid options including column definitions and types
  const colData: ColDef<Character>[] = [
    {field: 'id', headerName:'ID',sortable: true},
    {field: 'name', headerName:'Name',filter:true, editable: true},
    {field: 'status', headerName:'Status',editable: true, cellEditor: 'agSelectCellEditor', cellEditorParams: {values: ['Dead','Alive','Unknown']}}, 
    {field: 'species', headerName:'Species'}, 
    {field: 'gender', headerName:'Gender', editable: true, cellEditor: GenderDropdown }, 
    {field: 'location.name', headerName:'Current Location',type: "specialColumn"} 
    ]

    // Custom column types to handle editable logic and styling
    const columnTypes: any = {
      specialColumn:{
        editable: (params: {data: Character}) => {
          return isEditable(params) 
        },
        cellStyle: (params: {data: Character}) => {
          if(!isEditable(params)){
            return {backgroundColor: '#000000', color: '#ffffff'} // Style for non-editable cells
          }
        }
      }
    }
  
  // Fetching data from the API using the custom hook generated by RTK Query
  const {data} = useGetAllCharactersQuery()
  
  // Effect to update the row data when the API data changes
  useEffect(() => {
    if(data){
      setRowData(data.map(char => ({...char, location: {...char.location}})))
    }
  }, [data]);

  return(
      <AgGridProvider modules={modules}> 
        <div style={{height: 500}}>
          <AgGridReact<Character>
            theme = {themeBalham}
            rowData = {rowData}
            columnDefs = {colData}
            columnTypes={columnTypes}>
          </AgGridReact>
        </div>
      </AgGridProvider>
  )
}

export default App;
