import {AgGridProvider, AgGridReact} from 'ag-grid-react';
import { AllCommunityModule, CellValueChangedEvent, ValidationModule } from 'ag-grid-community';
import { SetFilterModule } from 'ag-grid-enterprise';
import { AllEnterpriseModule } from 'ag-grid-enterprise';
import { themeBalham } from 'ag-grid-community';
import { useEffect, useState } from 'react';
import {useGetAllCharactersQuery, Character} from './features/apiSlice';
import { useColumnDefs } from './hooks/useColumnDefs';

const modules = [AllCommunityModule, ValidationModule,SetFilterModule, AllEnterpriseModule];


export function App(){
  const [rowData, setRowData] = useState<Character[]>([]);   

  const {colData, columnTypes, defaultColDef} = useColumnDefs()

  
  // Fetching data from the API using the custom hook generated by RTK Query
  const {data} = useGetAllCharactersQuery()
  
  // Effect to update the row data when the API data changes
  useEffect(() => {
    if(data){
      setRowData(structuredClone(data))
    }
  }, [data]);

  function onCellValueChanged(params: CellValueChangedEvent<Character>){
    if(params.colDef.field === 'gender'){
      params.api.refreshCells({
        rowNodes: [params.node],
        columns: ['location.name'],
        force: true
      })
    }
  }

  return(
      <AgGridProvider modules={modules}> 
        <div style={{height: 500}}>
          <AgGridReact<Character>
            theme = {themeBalham}
            rowData = {rowData}
            columnDefs = {colData}
            columnTypes={columnTypes}
            defaultColDef = {defaultColDef}
            onCellValueChanged={onCellValueChanged}
            >
            
          </AgGridReact>
        </div>
      </AgGridProvider>
  )
}

export default App;
